### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by Ch00k** [guyzmo/pybitbucket#1]
Are there any plans to support Python 3.7?

**Comment by MrNocTV** [comment]
Looks like this project is dead, I'mt not sure the reason why, maybe because Bitbucket constantly changes their APIs.

**Comment by guyzmo** [comment]
it really is a fork of someone else's project, I did that fork to fix some stuff the original author did not merge in.
Though indeed, bitbucket changed its API a lot, mostly on the login side, to be integrated with atlassian's API and auth.
I'm not sure it works anymore, and I have no short term plan in working on it soon.

If there are PRs, I'd be happy to merge them in, though.
